### ISSUE TITLE
Data Access is not provided

### ISSUE THREAD

**Issue by JanvitaReddy** [mancinimassimiliano/CuMix#6]
G Drive folder is private. Please make it accessible for anyone

**Comment by mancinimassimiliano** [comment]
Hi @JanvitaReddy! Which folder are you referring to? As far as I remember, the only one linked from the code is the one of the PACS dataset ([here](https://drive.google.com/drive/folders/0B6x7gtvErXgfUU1WcGY5SzdwZVk?resourcekey=0-2fvpQY_QSyJf2uIECzqPuQ)) which is not private.
